
[server]
ip = '0.0.0.0'
port = 1080
client_dir = '../client'
websocket = true


[https]
enabled = true
port = 1443
key = './selfsig_keys/key.pem'
cert = './selfsig_keys/cert.pem'
fqdn = ''
keep_http = '/.well-known/acme-challenge/'


[auth]
enabled = false
realm = 'My site'
name = 'name'
password = 'password'

